
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-1
  labels:
    app: web-app-1
spec:
  selector:
    matchLabels:
        app: web-app-1
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-app-1
    spec:
      containers:
        - name: web-app-1
          image: 886059204444.dkr.ecr.us-east-2.amazonaws.com/meghatest:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
